config/routes.rb
Rails.application.routes.draw do
  
  resources :tags
  # Resources
  resources :lessons
  resources :users
  
  resources :sections do
    resources :lessons
  end
  resources :courses do
    resources :sections
  end
  
  # Home and session paths
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Lesson paths
  get '/compose_lesson', to: 'lessons#new'
  post '/lessons/:id', to: 'lessons#post_comment'
  
  # Course paths
  get '/compose_course', to: 'courses#new'
  post '/courses/section/new', to: 'courses#new_dynamic_section'
  
  # Search paths 
  #get '/search', to: 'lessons#search'
  get  '/search', to: "search#search"
  get 'search/search', to: "search#search"
  
  # Progress paths
  post 'progress/complete', to: 'progress#complete'
  post 'progress/undo', to: 'progress#undo'
  
end

app/models/section.rb
class Section < ApplicationRecord
  # Maybe change has_many to has_one :course_contents
  has_many :course_contents
  has_many :section_contents
  has_many :lessons, through: :section_contents
  belongs_to :course, required: false

  # Validates that the section's title exists
  validates :title, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  include SessionsHelper
  include SectionsHelper

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    #debugger
  end

  # GET /sections/new
  def new
    @section = Section.new
    
    @course = params['course_id']
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        # Add section to course.
        if params.has_key?('course_id')
          course_id = params['course_id']
          add_section_to_course(@section, course_id)
        end
        
        format.js { render "", json: @section }
      else
        format.js { render json: @section.errors, status: :unprocessable_entity }
      end
      # if add_section_to_course(@section, course_id)
      #   # Use the sections helper to create the relation between the section and its course.
      #   format.html { redirect_to Course.find(course_id), notice: 'Section was successfully created.' }
      #   format.json { render :show, status: :created, location: @section }
      # else
      #   format.html { render :new }
      #   format.json { render json: @section.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:title, :previous_id, :next_id, :course_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
  def add_section_to_course(section, course_id)
    #course_content = CourseContent.new({ :section_id => section.id, :course_id => course_id })
    course_content = CourseContent.new({section: section, course: Course.find(course_id)})

    #course_content.section.save
    #course_content.course.save

    course_content.save
  end

  def add_lesson_to_section(lesson, section_id)
    section_content = SectionContent.new({ :lesson_id => lesson.id, :section_id => section_id })

    if not section_content.save
      section_content.errors.full_messages.each do |msg|
        puts msg
      end
    end

    not section_content.errors.any?
  end
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div> -->

  <!-- <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div> -->

  <%= hidden_field_tag(:course_id, course_id) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Previous</th>
      <th>Next</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.previous_id %></td>
        <td><%= section.next_id %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1 class="center">New Section</h1>

<%= render 'form', section: @section, course_id: params['format'] %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Previous:</strong>
  <%= @section.previous_id %>
</p>

<p>
  <strong>Next:</strong>
  <%= @section.next_id %>
</p>


<%= debug @section %>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>