config/routes.rb
Rails.application.routes.draw do
  
  resources :tags
  # Resources
  resources :lessons
  resources :users
  
  resources :sections do
    resources :lessons
  end
  resources :courses do
    resources :sections
  end
  
  # Home and session paths
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Lesson paths
  get '/compose_lesson', to: 'lessons#new'
  post '/lessons/:id', to: 'lessons#post_comment'
  
  # Course paths
  get '/compose_course', to: 'courses#new'
  post '/courses/section/new', to: 'courses#new_dynamic_section'
  
  # Search paths 
  #get '/search', to: 'lessons#search'
  get  '/search', to: "search#search"
  get 'search/search', to: "search#search"
  
  # Progress paths
  post 'progress/complete', to: 'progress#complete'
  post 'progress/undo', to: 'progress#undo'
  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :section, required: false
  has_many :sections, :through => :section_contents
  has_many :comments

  # Lesson tag relations
  has_many :lesson_tags, inverse_of: :lesson
  has_many :tags, through: :lesson_tags 
  accepts_nested_attributes_for :lesson_tags

  # Validates that the article's title exists, is long enough, and is unique
  validates :title, presence: true#, length: { minimum: 6 }, uniqueness: true

  # Validates that the article has a sufficient body.
  #validates :body, presence: true, length: { minimum: 10 }

  # Validates that a user wrote the article.
  validates :user_id, presence: true

  # S3 attachments images/audio/video
  has_many_attached :attachments

  # ActionText rich text field
  has_rich_text :body
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  include SessionsHelper
  include SectionsHelper

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson_tags = @lesson.tags
    
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new

    @tags = Tag.all

    @lesson_tag = LessonTag.new

      
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    # The lesson has been composed by the signed-in user.
    @lesson.user_id = current_user.id

    # puts lesson_params
    # puts Tag.find_by(id: lesson_params[:tag_ids]).valid?
    # puts @lesson.valid?
    # puts @lesson.errors.full_messages
    respond_to do |format|
      if @lesson.save
        if params.has_key?('course')
          course_id = params['course']['course_id']
          section_id = params['course']['section_id']

          add_lesson_to_section(@lesson, section_id)
        end
        
        # Get the section, if present and add the lesson to it.
        if params.has_key?('section_id')
          section_id = params['section_id']
          add_lesson_to_section(@lesson, section_id)

          # Redirect to the course which contains the lesson.
          redirect_page = Section.find(section_id).course_contents.first.course
        else
          # Otherwise, just redirect to the lesson.
          redirect_page = @lesson
        end

        if not params.has_key?('no_redirect')
          format.html { redirect_to redirect_page }
        
          format.json { render :show, status: :created, location: @lesson }
        else
          format.js { render "", json: @lesson }
        end
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
        format.js { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    # First remove the lesson from any sections it's in.
    sections_contents = SectionContent.where(lesson_id: @lesson.id).each { |sc| sc.destroy }
    
    @lesson.destroy

    # Don't redirect anywhere if no_redirect is in the params.
    if params.has_key?('no_redirect')
      return
    end

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  # POST /lessons/1
  def post_comment
    @comment = Comment.new(comment_params)

    @comment.lesson_id = params[:id]
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = 'Comment posted!'
    else
      puts @comment.errors.full_messages
    end

    if params.has_key? "redirect_to"
      redirect_to Course.find(params["redirect_to"])
    else
      redirect_to Lesson.find(params[:id])
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :body, :tag_ids => [])
    end

    def comment_params
      params.permit(:text)
    end

    def sort
      params[:lesson].each_with_index do |id, index|
        Lesson.where('id = ?', id).update_all(position: index+1)
      end
      redirect_back(fallback_location: root_path)
      # render nothing: true
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  # Get n most recent lessons.
  def recent_lessons(n)
    Lesson.order('id desc').take(n)
  end

  # Get the first 100 characters from a lesson.
  def lesson_excerpt(lesson)
    lesson.body.body.to_s[0, 100] + '...'
  end

  def get_attachment_urls(lesson)
    # Return a list of the urls for a lesson's attachments.
    @lesson.attachments.map do |attachment|
      polymorphic_url(attachment, disposition: "attachment", only_path: true)
    end
  end

  def show_video(blob)
    path = 'C:\Users\Julian\Videos\Captures\romeo.mp4'
    #path = polymorphic_url(blob, disposition: "attachment")

    rails_blob_path(blob)
  end
end

app/views/lessons/_fancy_editor.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_with model: @lesson, local: true do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <br/>
      <%= f.label :body %>
      <%= f.rich_text_area :body %>

      <%= render :partial => "layouts/add_tag", :locals => { :f => f}%>

      <% if params.has_key?('lesson') %>
        <% if params['lesson'].has_key?('section_id') %>
          <%= hidden_field_tag(:section_id, params['lesson']['section_id']) %>
        <% end %>
      <% end %>

      

      <%= f.submit "Publish", class: "btn form-btn" %> 
    <% end %>
  </div>
</div>

app/views/lessons/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_with model: @lesson, local: true do |f| %>
      <%= render 'shared/lesson_error_messages' %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.text_area :body, size: "60x12", class: 'form-control' %>

      <%= f.file_field :attachments, multiple: true, direct_upload: true %>

      <% if params.has_key?('lesson') %>
        <% if params['lesson'].has_key?('section_id') %>
          <%= hidden_field_tag(:section_id, params['lesson']['section_id']) %>
        <% end %>
      <% end %>

      <%= f.submit "Publish", class: "btn form-btn" %> 
    <% end %>
  </div>
</div>

app/views/lessons/_lesson_content_partial.html.erb
<p id="notice"><%= notice %></p>

<script src="/js/show.js.erb"></script>
<script>

  $(document).ready(function () {
    AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');

    complete_button = document.getElementById("btn-complete[<%= lesson.id %>]");
    uncomplete_button = document.getElementById("btn-undo-complete[<%= lesson.id %>]");
    user_button = document.getElementById("user-button-<%= lesson.user.username %>");

    // Add complete/undo completion functionality to the buttons.
    $(complete_button).click(function () {
      $.ajax({
        type: "POST",
        url: "/progress/complete",
        data: {
          'lesson_id': <%= lesson.id %>,
          'authenticity_token': AUTH_TOKEN
        }
      })
    });

    $(uncomplete_button).click(function () {
      $.ajax({
        type: "POST",
        url: "/progress/undo",
        data: {
          'lesson_id': <%= lesson.id %>,
          'authenticity_token': AUTH_TOKEN
        }
      });
    });
  });
</script>


<div class="lesson-content">
  <div class="center lesson-show-head">
    <h2><%= lesson.title %></h2>
    <h4>
      <p>by: <a href="<%= user_path(lesson.user) %>"><%= lesson.user.username %></a></p>
    </h4>

    <%= render :partial => "layouts/tag_display_partial", locals: { :content => lesson } %>

  </div>

  <div id="user-modal" class="modal">
    <!-- Modal content -->
    <div class="user-modal-content">
      <div class="modal-header">
        <span class="close">&times;</span>
        <h2><%= link_to lesson.user.username, lesson.user %></h2>
      </div>
      <div class="modal-body">
        <p>This will contain more information about the user who wrote this lesson.</p>
      </div>
    </div>
  </div>

  <center>
    <% if course == nil %>
    <form action="">
      AUTO SCROLL
      <input type="button" id="auto-scroll-button" value="OFF" onclick="toggle(this);">
    </form>
    <% end %>
  </center>


  <br />

  <div class="lesson">
    <p>
      <%= lesson.body %>
    </p>
    <% if logged_in? %>
    <% if course != nil %>
    <% if current_user.id == course.user_id %>
    <button class="btn complete-button" id="btn-delete[<%= lesson.id %>]" type="button">Delete Lesson</button>
    <% end %>
    <% end %>
    <% end %>
  </div>

  <center>
    <% if logged_in? %>
    <% if !Set.new( Progress.where(user_id: current_user.id).map {|progress| progress.lesson_id}).include?(lesson.id) %>
    <button class="btn complete-button" id="btn-complete[<%= lesson.id %>]" type="button">Complete!</button>
    <%#= button_to 'Complete!', {:controller => "progress", :action => "complete"}, params: {lesson_id: lesson.id} %>
    <% else %>
    <button class="btn complete-button" id="btn-undo-complete[<%= lesson.id %>]" type="button">Undo Completion</button>
    <%#= button_to 'Undo Completion', {:controller => "progress", :action => "undo"}, params: {lesson_id: lesson.id} %>
    <% end %>
    <% else %>
    Log in to save progress!
    <% end %>
  </center>

  <div class="comment-section">
    <h3>Comments</h3>
    <div class="comment-form">
      <% if logged_in? %>
      <%= form_with model: @comment, url: lesson do |f| %>
      <%= f.text_area :text, class:"comment-text"%>
      <% if @course != nil %>
      <%= f.hidden_field(:redirect_to, value: @course.id) %>
      <% end %>

      <%= f.submit "Publish", class: "publish-btn btn comment-publish" %>
      <% end %>
      <% else %>
      Log in to post comments!
      <% end # if logged_in? %>
    </div>

    <br />
    <div class="comments-container">
      <% lesson.comments.each do |comment| %>
      <div class="comment-container">
        <strong><%= link_to  comment.user.username, comment.user %></strong>: <%= comment.text %>
      </div>
      <% end %>
    </div>
  </div>

  <div id="stop_scroll_notice"></div>
</div>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>
<%= %>
<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<body class="index">
  <p id="notice"><%= notice %></p>

  <h1 class="index">Lessons</h1>
  <hr>
  
  <center>
  <ul class="index">
      <% @lessons.each do |lesson| %>
        <li>
          <%= render :partial => "layouts/lesson_partial", :locals => { :lesson => lesson } %>
        </li>
      <% end %>
  </ul>
  </center>

  <br>

  <%= link_to 'New Lesson', new_lesson_path %>
</body>

app/views/lessons/new.html.erb
<h1 class="center">Compose Lesson</h1>

<%= render 'fancy_editor' %>

app/views/lessons/show.html.erb
<%= render partial: "lessons/lesson_content_partial", locals: { :lesson => @lesson, :course => nil } %>