config/routes.rb
Rails.application.routes.draw do
  
  resources :tags
  # Resources
  resources :lessons
  resources :users
  
  resources :sections do
    resources :lessons
  end
  resources :courses do
    resources :sections
  end
  
  # Home and session paths
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Lesson paths
  get '/compose_lesson', to: 'lessons#new'
  post '/lessons/:id', to: 'lessons#post_comment'
  
  # Course paths
  get '/compose_course', to: 'courses#new'
  post '/courses/section/new', to: 'courses#new_dynamic_section'
  
  # Search paths 
  #get '/search', to: 'lessons#search'
  get  '/search', to: "search#search"
  get 'search/search', to: "search#search"
  
  # Progress paths
  post 'progress/complete', to: 'progress#complete'
  post 'progress/undo', to: 'progress#undo'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  # No unbounded lessons; only lessons in sections are allowed
  belongs_to :user
  has_many :course_contents
  has_many :sections, through: :course_contents

  #course tag relations
  has_many :course_tags, inverse_of: :course
  has_many :tags, through: :course_tags
  accepts_nested_attributes_for :course_tags

  # Validates that the course's title exists
  validates :title, presence: true

  # Validates that a user started the course.
  validates :user_id, presence: true
end

app/models/course_content.rb
class CourseContent < ApplicationRecord
  belongs_to :section, required: false
  belongs_to :course, required: false
end

app/models/course_tag.rb
class CourseTag < ApplicationRecord
    belongs_to :course
    belongs_to :tag, inverse_of: :course_tags

    validates_presence_of :course
    validates_presence_of :tag

    accepts_nested_attributes_for :tag
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :section, required: false
  has_many :sections, :through => :section_contents
  has_many :comments

  # Lesson tag relations
  has_many :lesson_tags, inverse_of: :lesson
  has_many :tags, through: :lesson_tags 
  accepts_nested_attributes_for :lesson_tags

  # Validates that the article's title exists, is long enough, and is unique
  validates :title, presence: true#, length: { minimum: 6 }, uniqueness: true

  # Validates that the article has a sufficient body.
  #validates :body, presence: true, length: { minimum: 10 }

  # Validates that a user wrote the article.
  validates :user_id, presence: true

  # S3 attachments images/audio/video
  has_many_attached :attachments

  # ActionText rich text field
  has_rich_text :body
end

app/models/lesson_tag.rb
class LessonTag < ApplicationRecord
    belongs_to :lesson#, required: false
    belongs_to :tag, inverse_of: :lesson_tags#, required: false

    validates_presence_of :lesson
    validates_presence_of :tag

    accepts_nested_attributes_for :tag
end

app/models/progress.rb
class Progress < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  # Maybe change has_many to has_one :course_contents
  has_many :course_contents
  has_many :section_contents
  has_many :lessons, through: :section_contents
  belongs_to :course, required: false

  # Validates that the section's title exists
  validates :title, presence: true
end

app/models/section_content.rb
class SectionContent < ApplicationRecord
  belongs_to :section, required: false
  belongs_to :lesson
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :lesson_tags
    has_many :lessons, through: :lesson_tags
    #belongs_to :lessons, required: false

    has_many :course_tags
    has_many :courses, through: :course_tags
    #belongs_to :courses, required: false

    validates :name, presence: true, uniqueness: true

    before_save { name.downcase! }
end

app/models/user.rb
class User < ApplicationRecord
  #############
  # Relations #
  #############
  has_many :courses
  has_many :sections
  has_many :lessons
  
  ############################
  # Validations #
  ############################

  # Username validation
  validates :username, presence: true, length: { minimum: 3 }, uniqueness: true
  # Password validation
  validates :password, presence: true, length: { minimum: 6 }
  # Email validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
    length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true

  ############
  # Security #
  ############

  before_save { email.downcase! }
  has_secure_password

  #############
  # Functions #
  #############

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  # Get n most recent courses.
  def recent_courses(n)
    Course.order('id desc').take(n)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  # Get n most recent lessons.
  def recent_lessons(n)
    Lesson.order('id desc').take(n)
  end

  # Get the first 100 characters from a lesson.
  def lesson_excerpt(lesson)
    lesson.body.body.to_s[0, 100] + '...'
  end

  def get_attachment_urls(lesson)
    # Return a list of the urls for a lesson's attachments.
    @lesson.attachments.map do |attachment|
      polymorphic_url(attachment, disposition: "attachment", only_path: true)
    end
  end

  def show_video(blob)
    path = 'C:\Users\Julian\Videos\Captures\romeo.mp4'
    #path = polymorphic_url(blob, disposition: "attachment")

    rails_blob_path(blob)
  end
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
  def add_section_to_course(section, course_id)
    #course_content = CourseContent.new({ :section_id => section.id, :course_id => course_id })
    course_content = CourseContent.new({section: section, course: Course.find(course_id)})

    #course_content.section.save
    #course_content.course.save

    course_content.save
  end

  def add_lesson_to_section(lesson, section_id)
    section_content = SectionContent.new({ :lesson_id => lesson.id, :section_id => section_id })

    if not section_content.save
      section_content.errors.full_messages.each do |msg|
        puts msg
      end
    end

    not section_content.errors.any?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/tags_helper.rb
module TagsHelper
    # Get n most recent courses.
    def get_tags()
        Tag.all()
    end

    def get_important_tags(n)
        tags = get_n_tags(n)
        #want to have it so easy, intermediate, and hard are at top
    end

    def get_n_tags(n)
        tag_list = []
        tags = {}
        Tag.all.each do |tag|
            tags[tag] = tag.lessons.size + tag.courses.size
            puts tags[tag]
        end
        tags = Hash[tags.sort_by {|k,v| -v}]
        tags = tags.first(n)
        tags.each {|key| tag_list.append key[0]}
        tag_list
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<div class="attachment_display">
  <figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
    <% if blob.representable? %>
      <% if blob.video? %>
        <video width="800" height="600" controls>
          <source src="<%= blob.service_url %>" type="video/mp4">
        </video>
      <% else %>
        <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
      <% end %>
    <% end %>

    <figcaption class="attachment__caption">
      <% if caption = blob.try(:caption) %>
        <%= caption %>
      <% else %>
        <span class="attachment__name"><%= blob.filename %></span>
        <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
      <% end %>
    </figcaption>
  </figure>
</div>

app/views/layouts/_about.html.erb
<div class="about container-fluid">
    <h3 class="header">About Clef</h3>
    Clef is an online platform for people passionate about music. Create a lesson or a course today!
</div>

app/views/layouts/_add_tag.html.erb
<!--<script>
    $("#check-parent").on("click",function()) {
        if($("#check-parent").is(":checked")) {
            console.log("+ is checked");
            $("#tag-fields").show();
            $("#tag-fields .new-tag").prop("checked",true);
        }
        else {
            console.log("+ is unchecked");
            $("#tag-fields .new-tag").prop("checked",false);
            $("#tag-fields").hide();
        }
    });
</script> -->

<br/>
<hr>
<label class="tag-button">Select Course Tags<br />
<br />
<div class="wrapping">
    
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, {}, class: "toggle1" do |b| %>
        
            <%= b.check_box %>
            <%= b.label class:"toggle" do%>
                <%= b.text.upcase%>
            <% end %>
    <%end%>
    <!--<input type="checkbox" class="toggle1" id="check-parent"> 
    <label for="check-parent" class="toggle"> + </label>
    <div id="tag-fields">
        <%= render :partial => 'tags/form', :locals => { :tag => Tag.new} %>
    </div>-->
</div>




<!--<script type="text/javascript">
    $("input[type="checkbox"]+").on("change", function()){
        $(".tag_fields").toggle();
    });
</script>-->

app/views/layouts/_course_header.html.erb
<div class="course-header">
    <h1>
        <%= course.title %>
        <!-- <% course.tags.each do |tag| %>
        <span class="badge badge-secondary"><%= tag.name %></span>
        <% end %> %>-->
        <div class="course-wrap"> 
            <% course.tags.each do |content_tag| %>
                <%= link_to tags_path(:start => content_tag.id), class:"badge" do %>
                    <%= content_tag.name %>
                <% end %>
            <% end %>
        </div>
    </h1>
    <h4>By: <%= link_to User.find(course.user_id).username, User.find(course.user_id) %></h4>
    <h3><%= course.description  %></h3>
    <%= render :partial => "layouts/course_progress_bar", :locals => { :course => @course } %>

    <center>
        <form action="">
            AUTO SCROLL
            <input type="button" id="auto-scroll-button" value="OFF" onclick="toggle(this);">
        </form>
    </center>
</div>

app/views/layouts/_course_partial.html.erb
<%= link_to course, class:"card-link" do %>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"> <%= course.title %> </h4>
            
            <h6 class="card-subtitle mb-2 text-muted"> <%= course.user.username %> </h6>
            <p class="card-text"><%= course.description %></p>
        </div>
    </div>
<% end %> 

app/views/layouts/_course_progress_bar.html.erb
<% if logged_in? %>
  <% current_course_progress = (calculate_progress(course, current_user) * 100).to_i %>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="<%= current_course_progress %>"
    aria-valuemin="0" aria-valuemax="100" style="width:<%= current_course_progress %>%">
      <%= current_course_progress %>%
    </div>
  </div>
<% else %>
Log in to see progress!
<% end %>

app/views/layouts/_create_tags.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%=form.text_field :name, class:"remove-border", placeholder:"+ Add a New Tag"%>
  <!--<div class="new-tag">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="new-tag">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="new-tag">
    <%= form.submit %>
  </div>
  <input class="tag-btn" id="check-parent" placeholder="Add a New Tag">-->
<% end %>

app/views/layouts/_header.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container navbar-container">
    <%= link_to "Clef", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><a href="<%= lessons_path %>" class="btn nav-btn btn-outline-secondary"><i class="material-icons">description</i> Lessons</a></li>
            <li><a href="<%= courses_path %>" class="btn nav-btn"><i class="material-icons">library_books</i> Courses</a></li>
            <li><a href="<%= compose_course_path  %>" class="btn nav-btn"><i class="material-icons">library_add</i> Create Course</a></li>
            <li><a href="<%= compose_lesson_path %>" class="btn nav-btn"><i class="material-icons">note_add</i> Compose Lesson</a></li>
            <li><a href="<%= user_path(current_user) %>" class="btn nav-btn"><i class="material-icons">account_circle</i> Profile</a></li>
            <li><%= link_to logout_path, class: "btn nav-btn", method: :delete do %><i class="material-icons">exit_to_app</i> Logout<% end %></li>
          <% else %>
            <li><%= link_to signup_path, class: "btn nav-btn" do %> <i class="material-icons">eperson_add</i> Sign up<% end %></li>
            <li><%= link_to login_path, class: "btn nav-btn" do %><i class="material-icons">account_circle</i> Log In <% end %></li>
          <% end # if logged_in? %>
        </ul>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_home_search.html.erb
<div class="home-search container-fluid">
    <h3 class="home-search-h3">Looking for something specific?</h3>
    <div>
       <%= render :partial => 'layouts/search_partial' %> 
    </div>
    <div>
        <%= render :partial => 'layouts/tag_buttons', :locals => { :tags_to_show => tags_to_show}%>
    </div>
    
</div>

app/views/layouts/_lesson_partial.html.erb
<%= link_to lesson, class:"card-link" do %>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"> <%= lesson.title %> </h4>
            
            <h6 class="card-subtitle mb-2 text-muted"> <%= lesson.user.username %> </h6>
            <p class="card-text"><%= lesson_excerpt(lesson) %></p>
        </div>
    </div>
<% end %>  

app/views/layouts/_search_partial.html.erb
<%= form_tag(search_search_path, :method => "get",   class: 'navbar-form navbar-left') do %>  
  <div class="input-group" aria-label="search bar for courses">
    <%= search_field_tag :search_text, params[:search], placeholder: "Search for a lesson or course", class: "form-control" %>
    <!-- <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>  
    </div>   -->
  </div>  
<% end %>

app/views/layouts/_tag_buttons.html.erb
<div class="tag-buttons">
    <h3><%= link_to "Browse by category", "/tags", class:"link"%></h3>
    <% tags_to_show.each do |tag| %>
        
        <%= link_to tags_path(:start => tag.id), class:"tag-btn" do %>
            <div class="tag-button">
                <%= tag.name %>
                <!-- <%= link_to tag.name, tag, class: "tag-btn" %> -->
            </div>
        <% end %> 
        
    <% end %>
    
</div>

app/views/layouts/_tag_display_partial.html.erb
   
<h4>
    <% if content.tags.empty? %>
    No tags
    <% else %>
    <div class="wrapped"> 
        <% content.tags.each do |content_tag| %>
            <%= link_to tags_path(:start => content_tag.id), class:"badge" do %>
                <%= content_tag.name %>
            <% end %>
        <% end %>
    </div>
    <% end  %>
</h4>

app/views/layouts/_whats_new.html.erb
<div class="whatsnew container-fluid">
    <h3 class="whatsnew-header">What's new?</h3>
    <!-- <div class="container-fluid whatsnew-head-container">
        <div class="row header">
            <div class="header-label">
                <h3 class="whatsnew-header">What's new?</h3>
            </div>
            <div class="header-browse">
                <li><%= link_to "Browse Courses", courses_path, class: "btn btn-primary" %>
            </div>
        </div>
    </div> -->

    <ul class="index list-unstyled new-courses"></ul>
        <% new_courses.each do |course| %>
            <li>
                <%= render :partial => "layouts/course_partial", :locals => { :course => course } %>
            </li>
        <% end %>
    </ul>
</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Clef</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc="
    crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <script>
    var scrollTimeoutId;

    function startScroll() {
      if (document.getElementById("auto-scroll-button") != null) {
        if (document.getElementById("auto-scroll-button").value == "ON") {
          window.scrollBy(0, 1);
        }
        scrollTimeoutId = setTimeout(startScroll, 200);
      }
    };

    function stopScroll() {
      if (document.getElementById("auto-scroll-button") != null) {
        document.getElementById("auto-scroll-button").value = "OFF";
        clearTimeout(scrollTimeoutId);
        // document.getElementById('stop_scroll_notice').innerHTML = "Reached end of page. Turning off auto scroll.";
      }
    }

    // Modifications to default default methods so our desired functions execute at the desired time
    history.pushState = (f => function pushState() {
      var ret = f.apply(this, arguments);
      window.dispatchEvent(new Event('pushstate'));
      window.dispatchEvent(new Event('locationchange'));
      return ret;
    })(history.pushState);

    history.replaceState = (f => function replaceState() {
      var ret = f.apply(this, arguments);
      window.dispatchEvent(new Event('replacestate'));
      window.dispatchEvent(new Event('locationchange'));
      return ret;
    })(history.replaceState);

    window.addEventListener('popstate', () => {
      window.dispatchEvent(new Event('locationchange'))
    });

    window.addEventListener('locationchange', function () {
      stopScroll();
    })

    // Detects when a user has reached the end of the page and turns off autoscroll
    window.onscroll = function (ev) {
      if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
        stopScroll();
      }
    };

    // Toggles the passed button from OFF to ON and vice-versa.
    function toggle(button) {
      if (button.value == "OFF") {
        button.value = "ON";
        startScroll();
      } else {
        stopScroll();
      }
    };
  </script>
</body>

</html>

app/views/shared/_lesson_error_messages.html.erb
<% if @lesson.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@lesson.errors.count, "error") %>.
    </div>
    <ul>
    <% @lesson.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>